/* Limite de credito no Rio*/
SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes 
WHERE CIDADE = 'Rio de Janeiro'
GROUP BY BAIRRO;

SELECT ESTADO,BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes 
WHERE CIDADE = 'Rio de Janeiro'
GROUP BY ESTADO,BAIRRO
ORDER BY LIMITE_TOTAL DESC;

SELECT MAX(QUANTIDADE) AS MAIOR_QUANTIDADE FROM itens_notas_fiscais WHERE codigo_do_produto = '1101035' ;
