SELECT CURDATE();

SELECT current_timestamp();

SELECT ADDDATE("2017-06-15", INTERVAL 10 DAY);

SELECT ADDTIME("2017-06-15 09:34:21", "2");

SELECT DATEDIFF("2017-06-25", "2017-07-15");

SELECT DAYNAME ("2022-09-06");

SELECT datediff(CURRENT_TIMESTAMP(),'1992,08,11');

SELECT current_timestamp() AS DIA_HOJE, DATE_SUB(current_timestamp(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MÊS, YEAR(DATA_VENDA) AS ANO
 FROM NOTAS_FISCAIS;
 
 SELECT DISTINCT NOME, DATA_DE_NASCIMENTO ,
 TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO,CURDATE()) AS IDADE
 FROM tabela_de_clientes;